-- Define a custom type for user roles
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('member', 'admin', 'editor', 'moderator');
    END IF;
END $$;

-- Create a table to store user roles
CREATE TABLE public.user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE NOT NULL,
    role user_role DEFAULT 'member' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add comments to the table and columns for clarity
COMMENT ON TABLE public.user_roles IS 'Stores role information for each user.';
COMMENT ON COLUMN public.user_roles.user_id IS 'Foreign key to the authenticated user.';
COMMENT ON COLUMN public.user_roles.role IS 'The assigned role for the user.';

-- Create an index on user_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON public.user_roles(user_id);

-- Function to update the 'updated_at' timestamp on any row update
CREATE OR REPLACE FUNCTION public.update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to automatically update the 'updated_at' timestamp for user_roles
CREATE TRIGGER handle_user_roles_update
BEFORE UPDATE ON public.user_roles
FOR EACH ROW
EXECUTE FUNCTION public.update_modified_column();

-- Function to insert a new row into user_roles when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    admin_emails TEXT[];
BEGIN
    -- Get admin emails from environment variable, default to empty array if not set
    SELECT COALESCE(string_to_array(current_setting('app.settings.admin_emails', TRUE), ','), '{}') INTO admin_emails;

    -- Insert a new user role record
    INSERT INTO public.user_roles (user_id, role)
    VALUES (
        NEW.id,
        -- Assign 'admin' role if email is in the admin list, otherwise 'member'
        CASE
            WHEN NEW.email = ANY(admin_emails) THEN 'admin'::user_role
            ELSE 'member'::user_role
        END
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call handle_new_user on new user creation in auth.users
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();

-- Enable Row Level Security (RLS) for the user_roles table
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Allow users to view their own role
DROP POLICY IF EXISTS "Users can view their own roles" ON public.user_roles;
CREATE POLICY "Users can view their own roles"
ON public.user_roles
FOR SELECT
USING (user_id = auth.uid());

-- RLS Policy: Allow admins to view and manage all roles
DROP POLICY IF EXISTS "Admins can manage all roles" ON public.user_roles;
CREATE POLICY "Admins can manage all roles"
ON public.user_roles
FOR ALL
USING (
    EXISTS (
        SELECT 1
        FROM public.user_roles
        WHERE user_id = auth.uid() AND role = 'admin'
    )
);
