-- Define custom types
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE public.user_role AS ENUM ('member', 'admin');
    END IF;
END $$;

-- Table for user roles
CREATE TABLE public.user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    role user_role NOT NULL DEFAULT 'member'
);

COMMENT ON TABLE public.user_roles IS 'Stores user roles, linking back to Supabase auth.';

-- Table for daily task assignments
CREATE TABLE public.daily_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    instagram_id TEXT NOT NULL,
    assignment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.daily_assignments IS 'Tracks which Instagram accounts are assigned to which user each day.';
CREATE INDEX idx_daily_assignments_user_id_date ON public.daily_assignments(user_id, assignment_date);
CREATE INDEX idx_daily_assignments_instagram_id_date ON public.daily_assignments(instagram_id, assignment_date);


-- Table for application settings
CREATE TABLE public.app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL
);

COMMENT ON TABLE public.app_settings IS 'Stores application-wide configuration settings.';

-- Seed initial settings
INSERT INTO public.app_settings (key, value)
VALUES ('daily_assignments_per_member', '10')
ON CONFLICT (key) DO NOTHING;


-- Function to automatically insert a role for a new user
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'member');
    RETURN NEW;
END;
$$;

-- Trigger to execute the function on new user creation
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Grant usage on the public schema to the necessary roles
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO postgres, anon, authenticated, service_role;