--
-- Create a table for public profiles
--
create table if not exists users (
  id uuid references auth.users not null primary key,
  email varchar(255) unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table users enable row level security;
create policy "Public profiles are viewable by everyone." on users for select using (true);
create policy "Users can insert their own profile." on users for insert with check (auth.uid() = id);
create policy "Users can update own profile." on users for update using (auth.uid() = id);

--
-- Create a table for user roles
--
create table if not exists user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null constraint user_roles_user_id_fkey references auth.users(id) on delete cascade,
  role text not null default 'member',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id)
);
alter table user_roles enable row level security;

--
-- RLS POLICIES FOR user_roles
--

-- 1. Users can view their own role
create policy "Allow users to view their own role" on public.user_roles
for select to authenticated
using (auth.uid() = user_id);

-- 2. Admins can view and manage all roles
create policy "Allow admins to manage all roles" on public.user_roles
for all to authenticated
using (
  (select rol from public.user_roles where user_id = auth.uid()) = 'admin'
)
with check (
  (select rol from public.user_roles where user_id = auth.uid()) = 'admin'
);

--
-- Function to create a public user and a user_role entry
--
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  -- Create a public user profile
  insert into public.users (id, email)
  values (new.id, new.email);
  
  -- Create a role for the new user
  insert into public.user_roles (user_id, role)
  values (new.id, 'member');
  
  return new;
end;
$$;

--
-- Trigger to call handle_new_user on new user creation
--
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

--
-- Seed an admin user if it doesn't exist
--
DO $$
DECLARE
    admin_email TEXT := 'admin@sheetflow.app';
    admin_user_id UUID;
BEGIN
    -- Check if the user exists in auth.users
    SELECT id INTO admin_user_id FROM auth.users WHERE email = admin_email;

    -- If the user doesn't exist, you should create them via Supabase UI or client SDK first.
    -- This script assumes the user has been created and will now grant them an admin role.
    IF admin_user_id IS NOT NULL THEN
        -- Check if the user already has a role
        IF NOT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = admin_user_id) THEN
            -- If no role exists, insert the admin role
            INSERT INTO public.user_roles (user_id, role)
            VALUES (admin_user_id, 'admin');
        ELSE
            -- If a role exists, update it to admin
            UPDATE public.user_roles
            SET role = 'admin'
            WHERE user_id = admin_user_id;
        END IF;
        RAISE NOTICE 'Admin role ensured for %', admin_email;
    ELSE
        RAISE NOTICE 'Admin user % not found in auth.users. Please create the user first.', admin_email;
    END IF;
END $$;
